# Copyright (C) 2020 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.---

- name: import configurations
  import_playbook: settings.yml

- name: preconfigure linodes
  import_playbook: pre-config.yml

- hosts: mons mgrs osds mdss grafana-servers clients
  become: yes
  tasks:
  - name: setup mon-000 ssh key
    delegate_to: mon-000
    run_once: true
    community.crypto.openssh_keypair:
      path: /root/.ssh/id_ed25519
      type: ed25519
      comment: mon-000
    register: cephadm_key

  - name: register cephadm.id-ed25519 with hosts
    lineinfile:
      path: /root/.ssh/authorized_keys
      line: "{{ cephadm_key.public_key }}"

- hosts: mons clients
  become: yes
  tasks:
  - name: fetch cephadm
    become: no
    delegate_to: localhost
    run_once: true
    ansible.builtin.get_url:
      url: "https://download.ceph.com/rpm-{{ RELEASE }}/el9/noarch/cephadm"
      dest: "/tmp/cephadm-{{ RELEASE }}"
      mode: "0755"
      force: yes

  - name: distribute cephadm
    copy:
      dest: /root/cephadm
      group: root
      mode: 0755
      owner: root
      src: "/tmp/cephadm-{{ RELEASE }}"
      remote_src: false

- hosts: mon-000
  become: yes
  tasks:
  - name: reset cluster.spec (avoid mixed/invalid YAML from previous runs)
    file:
      path: /root/cluster.spec
      state: absent

  - name: read cluster.json (base)
    set_fact:
      cluster_cfg: "{{ lookup('file', 'cluster.json') | from_json }}"

  - name: locate osd node config (group=osds)
    set_fact:
      osd_node_cfg: >-
        {{
          (
            cluster_cfg.nodes
            | selectattr('group', 'equalto', 'osds')
            | list
            | first
          ) | default({}, true)
        }}

  - name: validate cluster.json has an osds node entry
    fail:
      msg: >-
        cluster.json is missing a nodes[] entry with "group": "osds".
        Add an OSD node definition that includes "osd_devices_by_host".
    when: (osd_node_cfg | length) == 0

  - name: read cluster.json (for per-host OSD devices)
    set_fact:
      osd_devices_by_host: "{{ osd_node_cfg.get('osd_devices_by_host', {}) }}"

  - name: validate every OSD host has a device list in cluster.json
    fail:
      msg: >-
        Missing OSD device list for host '{{ item }}'.
        Add it under nodes[].osd_devices_by_host in cluster.json, e.g.:
        "osd_devices_by_host": { "{{ item }}": ["/dev/sdX"] }
    loop: "{{ groups['osds'] }}"
    when:
      - groups['osds'] is defined
      - (osd_devices_by_host.get(item, []) | length) == 0

  - name: write cephadm spec (single clean YAML stream)
    copy:
      dest: /root/cluster.spec
      owner: root
      group: root
      mode: "0644"
      content: |
        {# Build a unique ordered list of all hosts we want in the spec #}
        {% set host_list = [] %}
        {% for g in ['mons','mgrs','osds','mdss','grafana-servers','clients'] %}
        {%   for h in groups.get(g, []) %}
        {%     if h not in host_list %}
        {%       set _ = host_list.append(h) %}
        {%     endif %}
        {%   endfor %}
        {% endfor %}

        {# Host specs #}
        {% for h in host_list %}
        {% if not loop.first %}---
        {% endif %}
        service_type: host
        hostname: {{ h }}
        addr: {{ hostvars[h]['ansible_ssh_host'] }}
        labels:
          - {{ hostvars[h]['ceph_group'] }}
        {% if hostvars[h]['ceph_group'] == 'mons' %}
          - _admin
        {% endif %}
        {% endfor %}

        ---
        service_type: mon
        placement:
          label: mons

        ---
        service_type: mgr
        placement:
          label: mgrs

        {# Per-host OSD service specs #}
        {% for h in groups.get('osds', []) %}
        ---
        service_id: {{ h }}
        service_type: osd
        placement:
          hosts:
            - {{ h }}
        data_devices:
          paths:
        {% for dev in osd_devices_by_host.get(h, []) %}
            - {{ dev }}
        {% endfor %}
        {% endfor %}

        ---
        service_id: all
        service_type: mds
        placement:
          label: mdss

  - name: "add {{ RELEASE }} repos"
    shell: "/root/cephadm add-repo {{ CEPHADM_REPO }}"

  - name: "install {{ RELEASE }}"
    shell: "/root/cephadm install ceph-common"

  - name: check ceph already bootstrapped
    stat:
      path: /etc/ceph/ceph.conf
    register: ceph_installed

  - name: "cephadm bootstrap"
    shell: "/root/cephadm bootstrap --mon-ip {{ monitor_address }} --ssh-private-key /root/.ssh/id_ed25519 --ssh-public-key /root/.ssh/id_ed25519.pub --apply-spec /root/cluster.spec"
    when: not ceph_installed.stat.exists

  - name: config public network
    shell: ceph config set global public_network 10.251.0.0/16

  - name: config cluster_network
    shell: ceph config set global cluster_network 10.251.0.0/16

  - name: log to files
    shell: ceph config set global log_to_file true

  - name: log cluster to file
    shell: ceph config set global mon_cluster_log_to_file true

  - name: disable stderr logging
    shell: ceph config set global log_to_stderr false

  - name: disable stderr logging of cluster log
    shell: ceph config set global mon_cluster_log_to_stderr false

- hosts: clients
  become: yes
  tasks:
  - name: "add {{ RELEASE }} repos"
    shell: "/root/cephadm add-repo {{ CEPHADM_REPO }}"

  - name: "install {{ RELEASE }}"
    shell: "/root/cephadm install ceph-common ceph-fuse"

  - name: generate min config
    shell: ceph config generate-minimal-conf
    delegate_to: mon-000
    register: minimal_config
    run_once: true

  - name: setup config
    copy:
      # yay ansible bug: https://github.com/ansible/ansible/issues/6077
      content: "{{ minimal_config.stdout }}\n"
      dest: /etc/ceph/ceph.conf
      owner: root
      group: root
      mode: 0644
