# Copyright (C) 2020 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.


# Configure firewalld on the cluster to only allow local private network
# traffic. We don't want the internet to have access to the cluster services.
# Although Ceph **is** configured to have its cluster_network/public_network on
# the Linode private LAN, some services still listen on all interfaces
# including grafana, prometheus, and the crash daemons.

- hosts: all
  become: yes
  tasks:
  - name: enable firewalld
    systemd:
      name: firewalld.service
      state: started
      enabled: yes

  - name: gather all network ranges from inventory
    set_fact:
      all_networks: >-
        {{
          (
            groups['all']
            | map('extract', hostvars)
            | map(attribute='public_network', default=None)
            | select('string')
            | list
            +
            groups['all']
            | map('extract', hostvars)
            | map(attribute='cluster_network', default=None)
            | select('string')
            | list
          )
          | unique
        }}
    run_once: true

  - name: allow traffic from cluster and public networks
    firewalld:
      source: "{{ item }}"
      zone: public
      state: enabled
      permanent: yes
      immediate: yes
    loop: "{{ all_networks | unique }}"

  - name: allow ssh
    firewalld:
      service: ssh
      zone: public
      state: enabled
      permanent: yes
      immediate: yes
